[INFO] [launch]: All log files can be found below /root/.ros/log/2023-07-23-01-12-42-163010-855f12e1d882-39485
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [robot_state_publisher-1]: process started with pid [39509]
[INFO] [gzserver-2]: process started with pid [39511]
[INFO] [gzclient-3]: process started with pid [39513]
[INFO] [spawn_entity.py-4]: process started with pid [39515]
[robot_state_publisher-1] [INFO] [1690074762.484734322] [robot_state_publisher]: got segment base_link
[robot_state_publisher-1] [INFO] [1690074762.484802442] [robot_state_publisher]: got segment chassis
[spawn_entity.py-4] [INFO] [1690074762.607321781] [spawn_entity]: Spawn Entity started
[spawn_entity.py-4] [INFO] [1690074762.607579593] [spawn_entity]: Loading entity published on topic robot_description
[spawn_entity.py-4] /opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/qos.py:307: UserWarning: DurabilityPolicy.RMW_QOS_POLICY_DURABILITY_TRANSIENT_LOCAL is deprecated. Use DurabilityPolicy.TRANSIENT_LOCAL instead.
[spawn_entity.py-4]   warnings.warn(
[spawn_entity.py-4] [INFO] [1690074762.608920927] [spawn_entity]: Waiting for entity xml on robot_description
[spawn_entity.py-4] [INFO] [1690074762.732999986] [spawn_entity]: Waiting for service /spawn_entity, timeout = 30
[spawn_entity.py-4] [INFO] [1690074762.733267206] [spawn_entity]: Waiting for service /spawn_entity
[gzserver-2] ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
[gzserver-2] ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
[gzserver-2] ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
[gzserver-2] ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
[gzserver-2] ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
[gzserver-2] ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
[gzserver-2] ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
[gzserver-2] ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM default
[gzserver-2] AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': No such file or directory
[spawn_entity.py-4] [INFO] [1690074762.987308566] [spawn_entity]: Calling service /spawn_entity
[spawn_entity.py-4] [INFO] [1690074763.206656911] [spawn_entity]: Spawn status: SpawnEntity: Successfully spawned entity [my_bot]
[INFO] [spawn_entity.py-4]: process has finished cleanly [pid 39515]
[gzclient-3] amdgpu: os_same_file_description couldn't determine if two DRM fds reference the same file description.
[gzclient-3] If they do, bad things may happen!
[WARNING] [launch]: user interrupted with ctrl-c (SIGINT)
[robot_state_publisher-1] [INFO] [1690074815.934607287] [rclcpp]: signal_handler(signum=2)
[INFO] [robot_state_publisher-1]: process has finished cleanly [pid 39509]
[INFO] [gzserver-2]: process has finished cleanly [pid 39511]
[ERROR] [gzclient-3]: process[gzclient-3] failed to terminate '5' seconds after receiving 'SIGINT', escalating to 'SIGTERM'
[INFO] [gzclient-3]: sending signal 'SIGTERM' to process[gzclient-3]
[ERROR] [gzclient-3]: process has died [pid 39513, exit code -15, cmd 'gzclient'].
