[INFO] [launch]: All log files can be found below /root/.ros/log/2023-07-23-01-11-42-760353-855f12e1d882-38195
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [robot_state_publisher-1]: process started with pid [38204]
[INFO] [gzserver-2]: process started with pid [38206]
[INFO] [gzclient-3]: process started with pid [38208]
[INFO] [spawn_entity.py-4]: process started with pid [38210]
[robot_state_publisher-1] [INFO] [1690074703.091804492] [robot_state_publisher]: got segment base_link
[robot_state_publisher-1] [INFO] [1690074703.091870337] [robot_state_publisher]: got segment chassis
[spawn_entity.py-4] [INFO] [1690074703.218981693] [spawn_entity]: Spawn Entity started
[spawn_entity.py-4] [INFO] [1690074703.219251759] [spawn_entity]: Loading entity published on topic robot_description
[spawn_entity.py-4] /opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/qos.py:307: UserWarning: DurabilityPolicy.RMW_QOS_POLICY_DURABILITY_TRANSIENT_LOCAL is deprecated. Use DurabilityPolicy.TRANSIENT_LOCAL instead.
[spawn_entity.py-4]   warnings.warn(
[spawn_entity.py-4] [INFO] [1690074703.220806357] [spawn_entity]: Waiting for entity xml on robot_description
[spawn_entity.py-4] [INFO] [1690074703.343937664] [spawn_entity]: Waiting for service /spawn_entity, timeout = 30
[spawn_entity.py-4] [INFO] [1690074703.344276231] [spawn_entity]: Waiting for service /spawn_entity
[gzserver-2] ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
[gzserver-2] ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
[gzserver-2] ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
[gzserver-2] ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
[gzserver-2] ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
[gzserver-2] ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
[gzserver-2] ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
[gzserver-2] ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM default
[gzserver-2] AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': No such file or directory
[spawn_entity.py-4] [INFO] [1690074703.598797172] [spawn_entity]: Calling service /spawn_entity
[spawn_entity.py-4] [INFO] [1690074703.809908627] [spawn_entity]: Spawn status: SpawnEntity: Successfully spawned entity [my_bot]
[INFO] [spawn_entity.py-4]: process has finished cleanly [pid 38210]
[gzclient-3] amdgpu: os_same_file_description couldn't determine if two DRM fds reference the same file description.
[gzclient-3] If they do, bad things may happen!
[WARNING] [launch]: user interrupted with ctrl-c (SIGINT)
[robot_state_publisher-1] [INFO] [1690074714.969240207] [rclcpp]: signal_handler(signum=2)
[INFO] [robot_state_publisher-1]: process has finished cleanly [pid 38204]
[INFO] [gzserver-2]: process has finished cleanly [pid 38206]
[INFO] [gzclient-3]: process has finished cleanly [pid 38208]
